name: Send Daily Quote

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

env:
  AUTH_USER: ${{secrets.AUTH_USER}}
  AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
  MAIL_FROM: ${{secrets.MAIL_FROM}}
  MAIL_BCC: ${{secrets.MAIL_BCC}}
  NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
  NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
  FIREBASE_APIKEY: ${{secrets.FIREBASE_APIKEY}}
  FIREBASE_MESSAGE_SENDER_ID: ${{secrets.FIREBASE_MESSAGE_SENDER_ID}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: node src/main.js
