name: Daily Report
on:
schedule:
cron: "0 14 * * *"
workflow_dispatch:
env:
AUTH_USER: ${{secret.AUTH_USER}}
          AUTH_TOKEN: ${{secret.AUTH_TOKEN}}
          MAIL_FROM: ${{secret.MAIL_FROM}}
          MAIL_TO: ${{secret.MAIL_TO}}
          NOTION_TOKEN: ${{secret.NOTION_TOKEN}}
          NOTION_DATABASE_ID: ${{secret.NOTION_DATABASE_ID}}
          FIREBASE_APIKEY: ${{secret.FIREBASE_APIKEY}}
          FIREBASE_MESSAGE_SENDER_ID: ${{secret.FIREBASE_MESSAGE_SENDER_ID}}
jobs:
report:
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [16.×]
steps:
uses: actions/checkout@v2
name: Use Node. js ${{ matrix. node-version }}
uses: actions/setup-node@v2
with:
node-version: ${{ matrix. node-version }}
run: npm ci
run: node src/main.js




          
